# Generated by Django 4.0.1 on 2022-01-17 03:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_category', models.CharField(db_index=True, max_length=100)),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.maincategory')),
            ],
            options={
                'verbose_name': 'Main_Category',
                'verbose_name_plural': 'Main_Categories',
                'ordering': ['main_category'],
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category', models.CharField(db_index=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Sub-Category',
                'verbose_name_plural': 'Sub-Categories',
                'ordering': ['sub_category'],
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default='Los Angeles', max_length=50, verbose_name='City')),
                ('product', models.CharField(max_length=100, verbose_name='Product')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('photo1', models.ImageField(blank=True, upload_to='item_pics/%Y/%m/%d', verbose_name='Pic 1')),
                ('photo2', models.ImageField(blank=True, upload_to='item_pics/%Y/%m/%d', verbose_name='Pic 2')),
                ('photo3', models.ImageField(blank=True, upload_to='item_pics/%Y/%m/%d', verbose_name='Pic 3')),
                ('photo4', models.ImageField(blank=True, upload_to='item_pics/%Y/%m/%d', verbose_name='Pic 4')),
                ('views', models.IntegerField(default=0)),
                ('main_category', models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, to='users.maincategory', verbose_name='Main Category')),
                ('sub_category', models.ForeignKey(default='21', on_delete=django.db.models.deletion.PROTECT, to='users.subcategory', verbose_name='Sub Categogry')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
